FROM ubuntu:18.04

WORKDIR /home/app
RUN apt-get update
RUN apt-get update && apt-get install -y --no-install-recommends apt-utils
RUN apt-get install -y python3.8
RUN apt-get install -y python3-pip=9.0.1-2.3~ubuntu1.20.04
RUN apt-get install -y net-tools 
RUN apt-get install -y dnsutils
RUN pip3 install pip==20.0.2
RUN pip3 install django==3.0.4
RUN pip3 install gunicorn==20.0.2
